# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - so101_right_arm_controller
    - so101_right_gripper_controller
    

  so101_right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_shoulder_pan
      - right_shoulder_lift
      - right_elbow_flex
      - right_wrist_flex
      - right_wrist_roll
      - right_gripper